Changed some testing.

diff --git a/dh-dyndns b/dh-dyndns
--- a/dh-dyndns
+++ b/dh-dyndns
@@ -26,9 +26,9 @@ EOL
 
 usage()
 {
-  # clear
-  printf -- "%s\n"
-  printf -- "%s\n" " "
+  cat <<EOL
+Usage : ${0##*/}
+EOL
 }
 
 failexit()
@@ -39,8 +39,9 @@ failexit()
 ### the meaty nougat begins here.
 
 # test for wget & uuidgen
-[[ ! -z $(which wget) ]] || { printf -- "%s\n" "Missing wget"; failexit; }
-[[ ! -z $(which uuidgen) ]] || { printf -- "%s\n" "Missing uuidgen"; failexit; }
+[ ! -z $(which wget) ] && WGET="wget -O- -q " ||
+  { printf -- "%s\n" "Missing wget"; failexit; }
+[ ! -z $(which uuidgen) ] || { printf -- "%s\n" "Missing uuidgen"; failexit; }
 
 case "$(uname 2>/dev/null)" in
   'Linux') TMP_FILE=$(mktemp --tmpdir dhdns.$$.XXXXXXXXXX);;
@@ -48,6 +49,7 @@ case "$(uname 2>/dev/null)" in
 esac
 trap "rm -rf ${TMP_FILE}" 0 1 2 3 15
 
+# process $# if exist
 while [ $# -ne 0 ]; do
   A=${1}; B=${2};
   case "${A}" in
@@ -59,17 +61,15 @@ while [ $# -ne 0 ]; do
   shift;
 done
 
-## set $KEY, $DOMAIN & $API address if not set at cli
+# this section assumes you have $# hardcoded
 [ -z ${KEY} ] && KEY="<SET API KEY HERE TO AUTOMATE>"
 [ -z ${DOMAIN} ] && DOMAIN="<DOMAIN NAME TO UPDATE>"
 [ -z ${API} ] && API="https://api.dreamhost.com/"
+# lets also set the wan ip check address
+[ -z ${wanIP} ] && wanIP="http://ipecho.net/plain"
 
-WGET="wget -O- -q "
-
-wanIP()
-{
-  wget http://ipecho.net/plain -O - -q | xargs
-}
+wanIP=$(wget http://ipecho.net/plain -O- -q) ||
+  { printf -- "%s\n" "cant grab wanip"; failexit; }
 
 listINFO()
 {
@@ -79,7 +79,7 @@ listINFO()
 
 diffINFO()
 {
-  if [ `wanIP` == `listINFO | awk '{ print $5 }'` ]; then
+  if [ ${wanIP} = `listINFO | awk '{ print $5 }'` ]; then
     printf -- "%s\n" "IP address is the same"
   else
     printf -- "%s\n" "IP address is different"
